/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logowanie użytkownika */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Zalogowano pomyślnie */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                /** @description Niepoprawne dane uwierzytelniające */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pobierz dane aktualnie zalogowanego użytkownika
         * @description Zwraca dane profilowe oraz role użytkownika wyciągnięte na podstawie tokenu JWT.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dane zalogowanego użytkownika */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserListItem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pobierz wszystkich użytkowników z możliwością filtrowania po frazie (search) */
        get: {
            parameters: {
                query?: {
                    /** @description Fraza wyszukiwania (dopasowuje fragment imienia, nazwiska lub adresu email) */
                    search?: string;
                    page?: number;
                    size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista zdenormalizowanych użytkowników */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserListPage"];
                    };
                };
            };
        };
        put?: never;
        /** Utwórz użytkownika */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserRequest"];
                };
            };
            responses: {
                /** @description Użytkownik utworzony */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pobierz użytkownika po ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Szczegóły użytkownika */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        /** Aktualizuj użytkownika */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserRequest"];
                };
            };
            responses: {
                /** @description Użytkownik zaktualizowany */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        post?: never;
        /** Usuń użytkownika */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Użytkownik usunięty */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/domains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pobierz listę domen */
        get: {
            parameters: {
                query?: {
                    /** @description Filtruj domeny po nazwie */
                    name?: string;
                    /** @description Numer strony (od 0) */
                    page?: number;
                    /** @description Liczba elementów na stronie */
                    size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista domen */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DomainPageDto"];
                    };
                };
            };
        };
        put?: never;
        /** Utwórz domenę */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DomainRequest"];
                };
            };
            responses: {
                /** @description Domena utworzona */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Domain"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/domains/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Aktualizuj domenę */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DomainRequest"];
                };
            };
            responses: {
                /** @description Domena zaktualizowana */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Domain"];
                    };
                };
            };
        };
        post?: never;
        /** Usuń domenę */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Domena usunięta */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expertise-levels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pobierz poziomy kompetencji */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista poziomów */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExpertiseLevel"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pobierz kompetencje konkretnego użytkownika */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista przypisań kompetencji dla wskazanego użytkownika */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserSkillDetail"][];
                    };
                };
            };
        };
        put?: never;
        /** Przypisz nową kompetencję użytkownikowi */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserSkillRequest"];
                };
            };
            responses: {
                /** @description Przypisanie utworzone */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user-skills/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Aktualizuj przypisanie kompetencji */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserSkillRequest"];
                };
            };
            responses: {
                /** @description Przypisanie zaktualizowane */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Usuń przypisanie kompetencji */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Przypisanie usunięte */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Wielokryterialne wyszukiwanie ekspertów
         * @description Umożliwia wyszukiwanie z użyciem operatorów logicznych (AND/OR) i relacyjnych (np. GTE).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExpertSearchRequest"];
                };
            };
            responses: {
                /** @description Wyniki wyszukiwania (paginowana lista użytkowników) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserListPage"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pobierz role użytkownika */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista ról przypisanych do użytkownika */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string[];
                    };
                };
            };
        };
        put?: never;
        /** Nadaj rolę użytkownikowi */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RoleRequest"];
                };
            };
            responses: {
                /** @description Rola przypisana pomyślnie */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}/roles/{roleName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Odbierz rolę użytkownikowi */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: number;
                    roleName: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Rola usunięta */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserRequest: {
            firstName: string;
            lastName: string;
            /** Format: email */
            email: string;
            active: boolean;
        };
        DomainPage: {
            content?: components["schemas"]["Domain"][];
            /** Format: int64 */
            totalElements?: number;
            totalPages?: number;
            size?: number;
            number?: number;
        };
        DomainPageDto: {
            content?: components["schemas"]["Domain"][];
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            number?: number;
            /** Format: int32 */
            size?: number;
        };
        User: {
            id?: number;
            firstName: string;
            lastName: string;
            email: string;
            active: boolean;
        };
        Domain: {
            id?: number;
            name?: string;
            description?: string;
        };
        ExpertiseLevel: {
            id?: number;
            name?: string;
            rankValue?: number;
        };
        UserSkill: {
            id?: number;
            userId?: number;
            domainId?: number;
            expertiseLevelId?: number;
        };
        UserSkillRequest: {
            userId?: number;
            domainId: number;
            expertiseLevelId: number;
        };
        RoleRequest: {
            /** @example ROLE_ADMIN */
            roleName: string;
        };
        LoginRequest: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /**
             * Format: password
             * @example Secret123!
             */
            password: string;
        };
        TokenResponse: {
            accessToken?: string;
        };
        UserSkillDetail: {
            id?: number;
            domainName?: string;
            levelName?: string;
            rankValue?: number;
        };
        /** @description Zagregowany obiekt DTO dla widoku listy, zapobiegający problemowi N+1. */
        UserListItem: {
            id: number;
            firstName: string;
            lastName: string;
            email: string;
            active: boolean;
            roles?: string[];
            skills?: components["schemas"]["UserSkillDetail"][];
        };
        UserListPage: {
            content?: components["schemas"]["UserListItem"][];
            totalElements?: number;
            totalPages?: number;
            size?: number;
            number?: number;
        };
        ExpertSearchCriteria: {
            /** @example Java */
            domainName: string;
            /** @example 3 */
            minRankValue: number;
            /**
             * @default GTE
             * @enum {string}
             */
            operator: "EQ" | "GTE";
        };
        ExpertSearchRequest: {
            criteria: components["schemas"]["ExpertSearchCriteria"][];
            /**
             * @example AND
             * @enum {string}
             */
            logicalOperator: "AND" | "OR";
        };
        DomainRequest: {
            name: string;
            description?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
